name = "argparse-f"
version = "0.1.0"
license = "license"
author = "0382"
maintainer = "18322825326@163.com"
copyright = "Copyright 2023, 0382"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"