name: msys2

on: [push, pull_request]

jobs:
  msys2-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          install: |
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-fpm
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-ninja

      - name: fpm test
        run: |
          fpm test
          fpm test -- -?
          fpm test -- -v

      - name: meson test
        run: |
          meson setup _build
          meson test -C _build
